# LASSO REGRESSION & RIDGE REGRESSION

In [1]:
#Import Libraries

In [2]:
#using %matplotlib inline code not required everytime to write plt.show()
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline 

In [3]:
#Import Data

In [4]:
cars = pd.read_csv('https://raw.githubusercontent.com/aishwaryamate/Datasets/main/cars.csv')

In [5]:
cars.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3                 ?  alfa-romero       gas  convertible   
1          3                 ?  alfa-romero       gas  convertible   
2          1                 ?  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [6]:
cars.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   symboling          205 non-null    int64  
 1   normalized-losses  205 non-null    object 
 2   make               205 non-null    object 
 3   fuel-type          205 non-null    object 
 4   body-style         205 non-null    object 
 5   drive-wheels       205 non-null    object 
 6   engine-location    205 non-null    object 
 7   width              205 non-null    float64
 8   height             205 non-null    float64
 9   engine-type        205 non-null    object 
 10  engine-size        205 non-null    int64  
 11  horsepower         205 non-null    object 
 12  city-mpg           205 non-null    int64  
 13  highway-mpg        205 non-null    int64  
 14  price              205 non-null    int64  
dtypes: float64(2), int64(5), object(8)
memory usage: 24.1+ KB


In [7]:
cars['normalized-losses'].value_counts()

?      41
161    11
91      8
150     7
134     6
128     6
104     6
85      5
94      5
65      5
102     5
74      5
168     5
103     5
95      5
106     4
93      4
118     4
148     4
122     4
83      3
125     3
154     3
115     3
137     3
101     3
119     2
87      2
89      2
192     2
197     2
158     2
81      2
188     2
194     2
153     2
129     2
108     2
110     2
164     2
145     2
113     2
256     1
107     1
90      1
231     1
142     1
121     1
78      1
98      1
186     1
77      1
Name: normalized-losses, dtype: int64

In [8]:
cars['horsepower'].value_counts()

68     19
70     11
69     10
116     9
110     8
95      7
88      6
62      6
101     6
160     6
114     6
84      5
97      5
102     5
145     5
82      5
76      5
111     4
92      4
123     4
86      4
90      3
73      3
85      3
207     3
182     3
121     3
152     3
112     2
56      2
161     2
156     2
94      2
52      2
?       2
162     2
155     2
184     2
100     2
176     2
55      1
262     1
134     1
115     1
140     1
48      1
58      1
60      1
78      1
135     1
200     1
64      1
120     1
72      1
154     1
288     1
143     1
142     1
175     1
106     1
Name: horsepower, dtype: int64

In [9]:
cars.replace('?',np.nan,inplace=True)

In [10]:
cars.head()

symboling normalized-losses         make fuel-type   body-style  \
0          3               NaN  alfa-romero       gas  convertible   
1          3               NaN  alfa-romero       gas  convertible   
2          1               NaN  alfa-romero       gas    hatchback   
3          2               164         audi       gas        sedan   
4          2               164         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

  horsepower  city-mpg  highway-mpg  price  
0        111        21           27  13495  
1        111        21           27  16500  
2        154        19           26  16500  
3        102        24           30  13950  
4        115        18           22  17450

In [11]:
from sklearn.impute import SimpleImputer

In [12]:
si = SimpleImputer(strategy='mean')

In [13]:
cars[['normalized-losses','horsepower']] = si.fit_transform(cars[['normalized-losses','horsepower']])

In [14]:
cars.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [15]:
cars.dtypes['normalized-losses']

dtype('float64')

In [16]:
cars.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

# Encoding

In [17]:
cars['make'].nunique()

22

In [18]:
from sklearn.preprocessing import OrdinalEncoder   #only on categorical column not numerical column

In [19]:
cars.head()

symboling  normalized-losses         make fuel-type   body-style  \
0          3              122.0  alfa-romero       gas  convertible   
1          3              122.0  alfa-romero       gas  convertible   
2          1              122.0  alfa-romero       gas    hatchback   
3          2              164.0         audi       gas        sedan   
4          2              164.0         audi       gas        sedan   

  drive-wheels engine-location  width  height engine-type  engine-size  \
0          rwd           front   64.1    48.8        dohc          130   
1          rwd           front   64.1    48.8        dohc          130   
2          rwd           front   65.5    52.4        ohcv          152   
3          fwd           front   66.2    54.3         ohc          109   
4          4wd           front   66.4    54.3         ohc          136   

   horsepower  city-mpg  highway-mpg  price  
0       111.0        21           27  13495  
1       111.0        21           27  16500  
2       154.0        19           26  16500  
3       102.0        24           30  13950  
4       115.0        18           22  17450

In [20]:
categorical_columns = cars.select_dtypes(object).columns

In [21]:
categorical_columns

Index(['make', 'fuel-type', 'body-style', 'drive-wheels', 'engine-location',
       'engine-type'],
      dtype='object')

In [22]:
oe = OrdinalEncoder()

In [23]:
cars[categorical_columns] = oe.fit_transform(cars[categorical_columns])

In [24]:
cars.head()

symboling  normalized-losses  make  fuel-type  body-style  drive-wheels  \
0          3              122.0   0.0        1.0         0.0           2.0   
1          3              122.0   0.0        1.0         0.0           2.0   
2          1              122.0   0.0        1.0         2.0           2.0   
3          2              164.0   1.0        1.0         3.0           1.0   
4          2              164.0   1.0        1.0         3.0           0.0   

   engine-location  width  height  engine-type  engine-size  horsepower  \
0              0.0   64.1    48.8          0.0          130       111.0   
1              0.0   64.1    48.8          0.0          130       111.0   
2              0.0   65.5    52.4          5.0          152       154.0   
3              0.0   66.2    54.3          3.0          109       102.0   
4              0.0   66.4    54.3          3.0          136       115.0   

   city-mpg  highway-mpg  price  
0        21           27  13495  
1        21           27  16500  
2        19           26  16500  
3        24           30  13950  
4        18           22  17450

# Model Building

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
X = cars.iloc[:,:-1]
Y = cars.iloc[:,-1]

In [27]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.25,random_state=1)

Linear Regression

In [28]:
from sklearn.linear_model import LinearRegression,Ridge , Lasso

In [29]:
lr = LinearRegression()

lr.fit(X_train,Y_train)
ylr = lr.predict(X_test)

print(lr.score(X_train,Y_train))
print(lr.score(X_test,Y_test))

0.8426404740417468
0.8174935371483154


In [30]:
lr.coef_

array([ 1.38883617e+01,  1.51670999e-01, -1.89831431e+02, -2.31217352e+02,
       -1.83043042e+02,  1.95544517e+03,  1.60171206e+04,  7.81040890e+02,
        3.22681962e+02,  3.62282035e+02,  9.74087263e+01, -1.12246223e+01,
        2.13785141e+02, -3.34637691e+02])

In [31]:
from sklearn.metrics import mean_squared_error , r2_score

In [32]:
from sklearn.metrics import mean_absolute_error

In [33]:
mse = mean_squared_error(Y_test,ylr)
mae = mean_absolute_error(Y_test,ylr)
rmse = np.sqrt(mse)

print('MAE: ',mae)
print('RMSE: ',rmse)
print('The mean squares value is :',mse)
print('The R2 score is:',r2_score(Y_test,ylr))

MAE:  2444.312260926019
RMSE:  3496.8563743028667
The mean squares value is : 12228004.50250259
The R2 score is: 0.8174935371483154


# Lasso Regression

In [34]:
lasso = Lasso()
lasso.fit(X_train,Y_train)

lassoy = lasso.predict(X_test)
print(lasso.score(X_train,Y_train))
print(lasso.score(X_test,Y_test))

0.8426390157329315
0.8175935442694683


In [35]:
lasso.coef_

array([ 1.39286215e+01,  1.54077958e-01, -1.89656037e+02, -2.23550176e+02,
       -1.83904868e+02,  1.95257503e+03,  1.59424807e+04,  7.78879640e+02,
        3.23327613e+02,  3.62475001e+02,  9.74964902e+01, -1.10978460e+01,
        2.12745858e+02, -3.33376536e+02])

In [36]:
for i in range(10,100):
    lasso = Lasso(alpha=i)
    lasso.fit(X_train,Y_train)
    
    lassoy = lasso.predict(X_test)
    trainac = lasso.score(X_train,Y_train)
    testac=lasso.score(X_test,Y_test)
    print(f" {i} Train {trainac} Test {testac} ")

 10 Train 0.8424946842827061 Test 0.818453017448295 
 11 Train 0.8424640722314876 Test 0.818543995924671 
 12 Train 0.8424305448974289 Test 0.8186340666435871 
 13 Train 0.8423941071644808 Test 0.8187232501536219 
 14 Train 0.8423547497202637 Test 0.8188115061654354 
 15 Train 0.8423124768736747 Test 0.818898854355521 
 16 Train 0.8422672952086006 Test 0.8189853172031648 
 17 Train 0.8422191921208134 Test 0.8190708506790065 
 18 Train 0.842168181277128 Test 0.8191554997039829 
 19 Train 0.8421142478611066 Test 0.8192392184175661 
 20 Train 0.8420574078291373 Test 0.8193220536057366 
 21 Train 0.8419976440045586 Test 0.8194039575434636 
 22 Train 0.8419349747898729 Test 0.8194849789234747 
 23 Train 0.8418693911814883 Test 0.8195650933245031 
 24 Train 0.8418008820693499 Test 0.8196442756332363 
 25 Train 0.8417294692821822 Test 0.8197225762328765 
 26 Train 0.8416551421078109 Test 0.8197999698572849 
 27 Train 0.8415778876089205 Test 0.8198764305191094 
 28 Train 0.841497731261317 Test

In [37]:
lasso = Lasso(alpha=99)
lasso.fit(X_train,Y_train)

lassoy = lasso.predict(X_test)
print(lasso.score(X_train,Y_train))
print(lasso.score(X_test,Y_test))

0.8288874977658719
0.8250504313581176


In [38]:
lr.coef_

array([ 1.38883617e+01,  1.51670999e-01, -1.89831431e+02, -2.31217352e+02,
       -1.83043042e+02,  1.95544517e+03,  1.60171206e+04,  7.81040890e+02,
        3.22681962e+02,  3.62282035e+02,  9.74087263e+01, -1.12246223e+01,
        2.13785141e+02, -3.34637691e+02])

In [39]:
lasso.coef_

array([ 9.47062926e+00,  5.17284285e-01, -1.73690901e+02, -0.00000000e+00,
       -2.84319223e+02,  1.60788183e+03,  8.46562205e+03,  5.32148945e+02,
        3.80069606e+02,  3.84827095e+02,  1.05708779e+02,  2.07456819e+00,
        8.63965993e+01, -1.99165752e+02])

# Ridge regression

In [40]:
ridge = Ridge()
ridge.fit(X_train,Y_train)
y_ridge = ridge.predict(X_test)
print(ridge.score(X_train,Y_train))
print(ridge.score(X_test,Y_test))

0.8363016020500668
0.8261721725797894


In [41]:
for i in range(10,100):
    ridge = Ridge(alpha=i)
    ridge.fit(X_train,Y_train)
    
    ridgeoy = ridge.predict(X_test)
    trainac = ridge.score(X_train,Y_train)
    testac=ridge.score(X_test,Y_test)
    print(f" {i} Train {trainac} Test {testac} ")

 10 Train 0.8061647370643804 Test 0.8299762200970315 
 11 Train 0.8049458666740463 Test 0.8298711335746745 
 12 Train 0.8038543918396157 Test 0.8297569030800483 
 13 Train 0.8028670720512683 Test 0.8296359698923725 
 14 Train 0.8019661462542139 Test 0.8295100889378364 
 15 Train 0.8011378128928273 Test 0.8293805609069157 
 16 Train 0.8003711855140285 Test 0.8292483745629626 
 17 Train 0.7996575602807223 Test 0.8291142973632271 
 18 Train 0.7989898926037378 Test 0.8289789351802441 
 19 Train 0.7983624168244545 Test 0.8288427729060448 
 20 Train 0.7977703655688985 Test 0.8287062028526304 
 21 Train 0.7972097597258309 Test 0.828569545134517 
 22 Train 0.7966772492432321 Test 0.8284330626415094 
 23 Train 0.7961699910124617 Test 0.8282969722705146 
 24 Train 0.7956855541738862 Test 0.8281614535107747 
 25 Train 0.7952218459421637 Test 0.8280266551169049 
 26 Train 0.7947770529582665 Test 0.8278927003732651 
 27 Train 0.7943495945121797 Test 0.8277596913019374 
 28 Train 0.7939380849287612 